name=input("Enter your name ")
clas=int(input("Enter your class "))
school=input("Enter your school name ")
age=int(input("Enter your age "))
city=input("Enter your city ")
print("Name-",name)
print("class-",clas)
print("school name-",school)
print("age-",age)
print("city",city)
